# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: cavcorpuzorg
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: translate-sample
# "service" is the name of this project. This will also be added to your AWS resource names.
service: translate-lambda

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: us-east-1

functions:
  hello:
    handler: app.server # reference the file and exported method
    events: # events trigger lambda functions
      - http: # this is an API Gateway HTTP event trigger
          path: /
          method: ANY
          cors: true
      - http: # all routes get proxied to the Express router
          path: /{proxy+}
          method: ANY
          cors: true
